// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewLaserProject.Data;

#nullable disable

namespace NewLaserProject.Migrations.WorkTimeDb
{
    [DbContext(typeof(WorkTimeDbContext))]
    [Migration("20240201111043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("NewLaserProject.Data.Models.WorkTimeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProcess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialName")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaterialThickness")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartApp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StopApp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechnologyName")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("YieldTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcessTimeLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
